codecov:
  token: # Optionnel : token pour projets privés (configuré via secrets.CODECOV_TOKEN)
  notify:
    wait_for_ci: true
  comment:
    layout: "reach,diff,flags,tree,reach"
    behavior: default
    require_changes: false

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        base: auto
        branches:
          - main
          - master
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
    
    patch:
      default:
        target: 80%
        threshold: 1%
        base: auto
        if_not_found: success
        if_ci_failed: error
        only_pulls: false

flags:
  unittests:
    paths:
      - backend/tests/
    carryforward: true
