# Generated by Django 5.1.5 on 2026-01-28 15:52

import apps.academic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_faculty_program_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='academic_rules_json',
            field=models.JSONField(default=dict, validators=[apps.academic.models.validate_academic_rules]),
        ),
    ]
