# Generated by Django 5.1.5 on 2026-01-28 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_alter_program_academic_rules_json'),
        ('core_identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3'), ('M1', 'M1'), ('M2', 'M2')], max_length=8)),
                ('finance_status', models.CharField(choices=[('OK', 'OK'), ('BLOQUE', 'Bloqué'), ('MORATOIRE', 'Moratoire')], max_length=16)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='academic.academicyear')),
            ],
            options={
                'db_table': 'REGISTRATION_ADMIN',
            },
        ),
        migrations.CreateModel(
            name='RegistrationPedagogical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaching_unit_id', models.UUIDField()),
                ('status', models.CharField(choices=[('VALIDE', 'Validé'), ('AJOURE', 'Ajourné')], max_length=16)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_units', to='academic.registrationadmin')),
            ],
            options={
                'db_table': 'REGISTRATION_PEDAGOGICAL',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=32, unique=True)),
                ('date_entree', models.DateField()),
                ('finance_status', models.CharField(choices=[('OK', 'OK'), ('BLOQUE', 'Bloqué'), ('MORATOIRE', 'Moratoire')], default='OK', max_length=16)),
                ('identity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='core_identity.coreidentity')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academic.program')),
            ],
            options={
                'db_table': 'STUDENT_PROFILE',
            },
        ),
        migrations.AddField(
            model_name='registrationadmin',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='academic.studentprofile'),
        ),
    ]
