# Generated by Django 5.1.5 on 2026-01-29 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_update_student_models_cahier_charges'),
        ('core_identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('credits', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Unité d'enseignement",
                'verbose_name_plural': "Unités d'enseignement",
                'db_table': 'TEACHING_UNIT',
                'ordering': ['code'],
            },
        ),
        migrations.AlterModelOptions(
            name='registrationadmin',
            options={'ordering': ['-registration_date', 'student'], 'verbose_name': 'Inscription administrative', 'verbose_name_plural': 'Inscriptions administratives'},
        ),
        migrations.AlterModelOptions(
            name='registrationpedagogical',
            options={'ordering': ['registration_admin', 'teaching_unit'], 'verbose_name': 'Inscription pédagogique', 'verbose_name_plural': 'Inscriptions pédagogiques'},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'ordering': ['-date_entree', 'matricule_permanent'], 'verbose_name': 'Profil étudiant', 'verbose_name_plural': 'Profils étudiants'},
        ),
        migrations.RemoveConstraint(
            model_name='registrationadmin',
            name='no_registration_if_blocked',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='solde',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Calculé via signal', max_digits=12),
        ),
        migrations.AlterField(
            model_name='registrationadmin',
            name='academic_year',
            field=models.ForeignKey(db_column='academic_year_id', on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='academic.academicyear'),
        ),
        migrations.AlterField(
            model_name='registrationadmin',
            name='finance_status',
            field=models.CharField(choices=[('OK', 'OK'), ('Bloqué', 'Bloqué'), ('Moratoire', 'Moratoire')], help_text='Synchronisé avec student.finance_status', max_length=20),
        ),
        migrations.AlterField(
            model_name='registrationadmin',
            name='level',
            field=models.CharField(choices=[('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3'), ('M1', 'M1'), ('M2', 'M2')], max_length=10),
        ),
        migrations.AlterField(
            model_name='registrationadmin',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='registrationadmin',
            name='student',
            field=models.ForeignKey(db_column='student_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='registrations_admin', to='academic.studentprofile'),
        ),
        migrations.AlterField(
            model_name='registrationpedagogical',
            name='registration_admin',
            field=models.ForeignKey(db_column='registration_admin_id', on_delete=django.db.models.deletion.CASCADE, related_name='pedagogical', to='academic.registrationadmin'),
        ),
        migrations.AlterField(
            model_name='registrationpedagogical',
            name='status',
            field=models.CharField(choices=[('En cours', 'En cours'), ('Validé', 'Validé'), ('Ajourné', 'Ajourné'), ('Dette', 'Dette')], default='En cours', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='academic_status',
            field=models.CharField(choices=[('Actif', 'Actif'), ('Ajourné', 'Ajourné'), ('Exclu', 'Exclu')], default='Actif', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='current_program',
            field=models.ForeignKey(blank=True, db_column='current_program_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academic.program'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='finance_status',
            field=models.CharField(choices=[('OK', 'OK'), ('Bloqué', 'Bloqué'), ('Moratoire', 'Moratoire')], default='OK', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='matricule_permanent',
            field=models.CharField(db_column='matricule_permanent', max_length=20, unique=True),
        ),
        migrations.AddIndex(
            model_name='registrationadmin',
            index=models.Index(fields=['student', 'academic_year'], name='REGISTRATIO_student_904687_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationadmin',
            index=models.Index(fields=['finance_status'], name='REGISTRATIO_finance_d30be4_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['matricule_permanent'], name='STUDENT_PRO_matricu_5b7924_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['finance_status'], name='STUDENT_PRO_finance_d73fc7_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['academic_status'], name='STUDENT_PRO_academi_501150_idx'),
        ),
        migrations.AddConstraint(
            model_name='registrationadmin',
            constraint=models.CheckConstraint(condition=models.Q(('finance_status', 'Bloqué'), _negated=True), name='no_registration_if_blocked'),
        ),
        migrations.AddField(
            model_name='teachingunit',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_units', to='academic.program'),
        ),
        migrations.AlterField(
            model_name='registrationpedagogical',
            name='teaching_unit',
            field=models.ForeignKey(db_column='teaching_unit_id', on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='academic.teachingunit'),
        ),
        migrations.AddIndex(
            model_name='registrationpedagogical',
            index=models.Index(fields=['registration_admin', 'teaching_unit'], name='REGISTRATIO_registr_4c6901_idx'),
        ),
        migrations.AddIndex(
            model_name='registrationpedagogical',
            index=models.Index(fields=['status'], name='REGISTRATIO_status_60ccc7_idx'),
        ),
    ]
