# Generated by Django 5.1.5 on 2026-02-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_teachingunit_alter_registrationadmin_options_and_more'),
        ('core_identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingunit',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='taught_teaching_units', to='core_identity.coreidentity'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='finance_status',
            field=models.CharField(choices=[('OK', 'OK'), ('Bloqué', 'Bloqué'), ('Moratoire', 'Moratoire')], db_index=True, default='OK', max_length=20),
        ),
    ]
