# Generated by Django 5.1.5 on 2026-02-03 13:27

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_courseelement_alter_evaluation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(help_text='Année académique (ex: 2024-2025)', max_length=16)),
                ('inscription_iuec', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('inscription_tutelle', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('inscription_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('echeance_inscription', models.DateField(blank=True, null=True)),
                ('scolarite_tranche1', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('scolarite_tranche2', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('scolarite_tranche3', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('scolarite_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('echeances_scolarite', models.JSONField(default=list, help_text="Liste des dates d'échéances de scolarité")),
                ('autres_frais', models.JSONField(default=dict, help_text="Autres frais spécifiques (kits, blouses, matières d'œuvre, etc.)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(db_column='program_id', on_delete=django.db.models.deletion.CASCADE, related_name='frais', to='academic.program')),
            ],
            options={
                'verbose_name': 'Frais',
                'verbose_name_plural': 'Frais',
                'db_table': 'FRAIS',
                'indexes': [models.Index(fields=['program', 'academic_year'], name='FRAIS_program_54c3a3_idx')],
                'unique_together': {('program', 'academic_year')},
            },
        ),
    ]
