# Generated by Django 5.1.5 on 2026-02-03 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0010_frais'),
        ('core_identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moratoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_reporte', models.DecimalField(decimal_places=2, help_text='Montant du solde reporté par le moratoire', max_digits=12)),
                ('date_accord', models.DateTimeField(auto_now_add=True, help_text="Date et heure d'accord du moratoire")),
                ('date_fin', models.DateField(help_text='Date de fin du moratoire (date_accord + duree_jours)')),
                ('duree_jours', models.PositiveIntegerField(choices=[(30, '30 jours'), (60, '60 jours'), (90, '90 jours')], default=30, help_text='Durée du moratoire en jours')),
                ('motif', models.TextField(blank=True, help_text='Motif du moratoire (ex: Difficultés financières, Raison familiale)')),
                ('statut', models.CharField(choices=[('Actif', 'Actif'), ('Respecté', 'Respecté'), ('Dépassé', 'Dépassé')], db_index=True, default='Actif', max_length=20)),
                ('created_by_role', models.CharField(help_text='Rôle actif lors de la création (pour audit)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accorde_par', models.ForeignKey(db_column='accorde_par_id', help_text='Identité de la personne ayant accordé le moratoire', on_delete=django.db.models.deletion.PROTECT, related_name='moratoires_accordes', to='core_identity.coreidentity')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='moratoires', to='academic.studentprofile')),
            ],
            options={
                'verbose_name': 'Moratoire',
                'verbose_name_plural': 'Moratoires',
                'db_table': 'MORATOIRE',
                'ordering': ['-date_accord'],
                'indexes': [models.Index(fields=['student', 'statut'], name='MORATOIRE_student_407ed1_idx'), models.Index(fields=['date_fin'], name='MORATOIRE_date_fi_ea14d3_idx')],
            },
        ),
    ]
