# Generated by Django 5.1.5 on 2026-02-04 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0011_add_moratoire_model'),
        ('core_identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_bourse', models.CharField(choices=[('Merite', 'Mérite académique'), ('Besoin', 'Besoins sociaux'), ('Tutelle', 'Bourse tutelle/université partenaire'), ('Externe', 'Bourse externe (ONG, État, etc.)'), ('Interne', 'Bourse IUEC interne')], help_text='Type de bourse accordée', max_length=50)),
                ('montant', models.DecimalField(decimal_places=2, help_text='Montant total de la bourse', max_digits=12)),
                ('pourcentage', models.DecimalField(blank=True, decimal_places=2, help_text='Pourcentage de réduction (ex: 50.00 pour 50%)', max_digits=5, null=True)),
                ('date_attribution', models.DateTimeField(auto_now_add=True, help_text="Date et heure d'attribution de la bourse")),
                ('date_fin_validite', models.DateField(blank=True, help_text="Date de fin de validité (ex: fin d'année ou semestre)", null=True)),
                ('motif', models.TextField(blank=True, help_text="Motif d'attribution de la bourse")),
                ('statut', models.CharField(choices=[('Active', 'Active'), ('Suspendue', 'Suspendue'), ('Terminee', 'Terminée')], db_index=True, default='Active', help_text='Statut de la bourse', max_length=20)),
                ('conditions', models.JSONField(blank=True, default=dict, help_text="Conditions de maintien (ex: {'moyenne_min': 12, 'assiduite_min': 80})")),
                ('created_by_role', models.CharField(blank=True, help_text='Rôle actif lors de la création (pour audit)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accorde_par', models.ForeignKey(db_column='accorde_par_id', help_text='Identité de la personne ayant accordé la bourse', on_delete=django.db.models.deletion.PROTECT, related_name='bourses_accordees', to='core_identity.coreidentity')),
                ('annee_academique', models.ForeignKey(db_column='academic_year_id', on_delete=django.db.models.deletion.PROTECT, related_name='bourses', to='academic.academicyear')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='bourses', to='academic.studentprofile')),
            ],
            options={
                'verbose_name': 'Bourse',
                'verbose_name_plural': 'Bourses',
                'db_table': 'BOURSE',
                'ordering': ['-date_attribution'],
                'indexes': [models.Index(fields=['student', 'statut'], name='BOURSE_student_adcb45_idx'), models.Index(fields=['annee_academique', 'statut'], name='BOURSE_academi_7c8d64_idx'), models.Index(fields=['date_fin_validite'], name='BOURSE_date_fi_89be06_idx')],
            },
        ),
    ]
