# Generated by Django 5.1.5 on 2026-02-04 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_bourse'),
        ('core_identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_demande', models.CharField(choices=[('Releve', 'Relevé de notes'), ('Certificat', 'Certificat de scolarité'), ('Moratoire', 'Demande de moratoire'), ('Bourse', 'Demande de bourse'), ('Autre', 'Autre demande')], help_text='Type de demande', max_length=50)),
                ('motif', models.TextField(help_text='Motif de la demande')),
                ('piece_jointe', models.FileField(blank=True, help_text='Pièce jointe optionnelle', null=True, upload_to='student_requests/')),
                ('statut', models.CharField(choices=[('En_attente', 'En attente'), ('En_cours', 'En cours de traitement'), ('Traitee', 'Traitée'), ('Rejetee', 'Rejetée')], db_index=True, default='En_attente', max_length=20)),
                ('reponse', models.TextField(blank=True, help_text="Réponse de l'administration")),
                ('date_traitement', models.DateTimeField(blank=True, help_text='Date de traitement', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='academic.studentprofile')),
                ('traite_par', models.ForeignKey(blank=True, db_column='traite_par_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_traitees', to='core_identity.coreidentity')),
            ],
            options={
                'verbose_name': 'Demande étudiante',
                'verbose_name_plural': 'Demandes étudiantes',
                'db_table': 'STUDENT_REQUEST',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'statut'], name='STUDENT_REQ_student_59b580_idx'), models.Index(fields=['type_demande', 'statut'], name='STUDENT_REQ_type_de_2b71ec_idx')],
            },
        ),
    ]
