# Generated by Django 5.1.5 on 2026-02-04 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0013_studentrequest'),
        ('core_identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeAdministrative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_demande', models.CharField(choices=[('Releve_notes', 'Relevé de notes'), ('Certificat_scolarite', 'Certificat de scolarité'), ('Attestation_reussite', 'Attestation de réussite'), ('Autre', 'Autre (préciser)')], help_text='Type de demande administrative', max_length=50)),
                ('motif', models.TextField(help_text='Motif de la demande')),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Approuvée', 'Approuvée'), ('Rejetée', 'Rejetée')], db_index=True, default='En attente', max_length=20)),
                ('date_soumission', models.DateTimeField(auto_now_add=True, help_text='Date et heure de soumission')),
                ('date_traitement', models.DateTimeField(blank=True, help_text='Date et heure de traitement', null=True)),
                ('piece_jointe', models.FileField(blank=True, help_text='Pièce jointe optionnelle', null=True, upload_to='demandes/')),
                ('commentaire', models.TextField(blank=True, help_text="Commentaire de l'administration")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='academic.studentprofile')),
                ('traite_par', models.ForeignKey(blank=True, db_column='traite_par_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_traitees', to='core_identity.coreidentity')),
            ],
            options={
                'verbose_name': 'Demande administrative',
                'verbose_name_plural': 'Demandes administratives',
                'db_table': 'DEMANDE_ADMINISTRATIVE',
                'ordering': ['-date_soumission'],
                'indexes': [models.Index(fields=['student', 'statut'], name='DEMANDE_ADM_student_371d2d_idx'), models.Index(fields=['type_demande', 'statut'], name='DEMANDE_ADM_type_de_710a4e_idx'), models.Index(fields=['date_soumission'], name='DEMANDE_ADM_date_so_aa55c0_idx')],
            },
        ),
    ]
